// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5C9iYKbQ9IdLxpuqGJJjJte2uVBtvWuE',
    appId: '1:246586820110:web:793ac08027e110ce4dde5f',
    messagingSenderId: '246586820110',
    projectId: 'garden-api-cf2ec',
    authDomain: 'garden-api-cf2ec.firebaseapp.com',
    storageBucket: 'garden-api-cf2ec.firebasestorage.app',
    measurementId: 'G-R74Q2CLQ0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcSTYHoU9M71LHn4gNUDYMJ47ss1OhgCs',
    appId: '1:246586820110:android:6af7809b50743abd4dde5f',
    messagingSenderId: '246586820110',
    projectId: 'garden-api-cf2ec',
    storageBucket: 'garden-api-cf2ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjNzkMXx3gzCakwXBxHM13uJyi6UREw80',
    appId: '1:246586820110:ios:8396a8f8dbe8a0544dde5f',
    messagingSenderId: '246586820110',
    projectId: 'garden-api-cf2ec',
    storageBucket: 'garden-api-cf2ec.firebasestorage.app',
    iosBundleId: 'com.example.plantDb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5C9iYKbQ9IdLxpuqGJJjJte2uVBtvWuE',
    appId: '1:246586820110:web:85c8425c6e4990d44dde5f',
    messagingSenderId: '246586820110',
    projectId: 'garden-api-cf2ec',
    authDomain: 'garden-api-cf2ec.firebaseapp.com',
    storageBucket: 'garden-api-cf2ec.firebasestorage.app',
    measurementId: 'G-0TWM81QZZP',
  );

}